version: '3.3'
services:
  mysqldb:
    image: mysql:8.0
    container_name: zipa_database_service
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db:/var/lib/mysql
      - ./dbinit.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db: